runtime: nodejs20
env: standard

instance_class: F1

handlers:
  # Serve static files from dist directory
  - url: /assets
    static_dir: dist/assets
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2|ttf|eot|json|xml|txt))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|svg|webp|ico|woff|woff2|ttf|eot|json|xml|txt))
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # SPA fallback - serve index.html for all other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: "public, max-age=0, must-revalidate"

env_variables:
  NODE_ENV: "production"
  CI: "true"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7

network:
  session_affinity: false
