# 🚨 BULLETPROOF APP HOSTING CONFIGURATION
# Souk El-Syarat Marketplace Backend Services

apiVersion: v1
kind: Backend
metadata:
  name: souk-el-sayarat-backend
  region: europe-west4
spec:
  source:
    repository: https://github.com/AmrNabih-hub/Souk-El-Syarat
    branch: main
    rootDir: functions
  runtime: nodejs18
  env:
    - name: NODE_ENV
      value: production
    - name: FIREBASE_PROJECT_ID
      value: souk-el-syarat
  scaling:
    minInstances: 0
    maxInstances: 10
    concurrency: 80
  resources:
    cpu: 1
    memory: 512Mi
  timeout: 60s
  secrets:
    - name: FIREBASE_SERVICE_ACCOUNT
      secretName: firebase-service-account
  healthCheck:
    path: /health
    initialDelay: 10s
    period: 30s
    timeout: 5s
    failureThreshold: 3
  rolloutPolicy:
    type: immediate
    trafficPercentage: 100