mutation AddProductListing($data: ProductListing_Data!) @auth(level: USER) {
  productListing_insert(data: $data)
}

query GetProductListing($id: UUID!) @auth(level: PUBLIC) {
  productListing(id: $id) {
    id
    title
    description
    price
    currency
    images
    isAvailable
    category
    location
    vendor {
      id
      displayName
    }
    createdAt
  }
}

query ListProductListings @auth(level: PUBLIC) {
  productListings {
    id
    title
    description
    price
    currency
    images
    isAvailable
    category
    location
    vendor {
      id
      displayName
    }
    createdAt
  }
}

mutation UpdateProductListing($id: UUID!, $data: ProductListing_Data!) @auth(level: USER) {
  productListing_update(id: $id, data: $data)
}